<div id="anchor-content" class="middle">
    <div id="page:main-container">
        <div class="content-header">
            <table cellspacing="0">
                <tbody>
                    <tr>
                        <td style="width:50%;">
                            <h3 class="icon-head head-adminhtml-banner">
                                <?php echo $this->__('Abandoned Report') ?>
                            </h3>
                        </td>
                        <td class="form-buttons">
                            <button style="" onclick="showAbandonedReport()" class="scalable add"
                                    type="button" title="<?php echo $this->__("Show Report") ?>" id="abandoned_report_btn">
                                <span>
                                    <span>
                                        <span><?php echo $this->__("Show Report") ?></span>
                                    </span>
                                </span>
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div>
            <?php echo $this->getChildHtml('report_filter'); ?>
        </div>
        <div id="chart_div" class="report-content clear report-chart">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script>google.charts.load('current', {'packages': ['corechart']});</script>
        </div>
    </div>
</div>
<script type="text/javascript">
    var reportUrl = '<?php echo Mage::getUrl('adminhtml/abandoned_report/search') ?>';
    var FORM_KEY = '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>';
    function showAbandonedReport(){
        var filterForm = new varienForm('filter_form', '');
        if(!filterForm.validate())
            return;
        var params = Form.serializeElements($('filter_form')
                .select('input', 'select', 'textarea'), true);
        
        params.form_key = FORM_KEY;
        new Ajax.Request(reportUrl,{
            parameters :params,
            method :'post',
            area :$(this.idPrefix + 'simple_form'),
            onComplete : function(xhr){
                if(!xhr.responseText)
                    return;
                var result = JSON.parse(xhr.responseText);
                var data = [['Time', 'Count Success', 'Total Money', 'Total Discount']];
                var total = 0;
                for (var i = 0; i < result.timeArray.length; i++) {
                    var count_sucesss = Number.parseInt(result.countSuccess[i]);
                    var total_money = result.sumTotal[i];
                    var total_discount = result.sumDiscount[i];
                    data.push([result.timeArray[i], count_sucesss, total_money, total_discount]);
                    total += count_sucesss;
                }
                var data = google.visualization.arrayToDataTable(data);
                var options = {
                    title: 'Total records: ' + total,
                    hAxis: {title: 'Time', titleTextStyle: {color: '#333'}},
                    vAxis: {minValue: 0}
                };
                var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
                chart.draw(data, options);
            }
        })
    }
</script>
    